SECRET_KEY = "TMgW4cECe234i20945u3sRw*4!rP2352!$!$%&7ñPKNJNDFWOM9qnnf$B"
MODEL = "data/model/model.pkl"
HOST = "database-poc.ceeicqti4fmz.eu-west-3.rds.amazonaws.com"
USER = "adminpoc"
PASSWORD = "adminpoc"